### PR TITLE
Feature/xvf3610 support

### PR DESCRIPTION
**Pull request by DaveAtkinsonXMOS**
Add support for xvf3610

### CODE REVIEW

**Review by lucianomartin — COMMENTED** [review]
Changes look good.
@DaveAtkinsonXMOS, do you think we can address this issue in the PR:
https://github.com/xmos/vocalfusion-avs-setup/issues/34

**Comment by DaveAtkinsonXMOS** [comment]
Yes of course...

**Review by lucianomartin — APPROVED** [review]
Changes are ok.
Line 10 of auto_install.sh must be updated before merging.

**Review by lucianomartin — APPROVED** [review]
Looks good!

**Review by mbanth — APPROVED** [review]

**Pull request merged**
